#server.port=8888
#spring.jpa.hibernate.ddl-auto=create
spring:
  main:
    allow-circular-references: true
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8888